#!/bin/bash

# Copy paths of the selected files to the clipboard

# Exit the script on any errors as this will run in the background, we don't want it to be stuck and taking up memory
set -e  # Causes the script to exit im immediately if there are any errors.
set -u  # Causes the script to exit if we do not define a variable when it is expanded.
set -o pipefail # Makes sure that if any part of a pipeline fails, the script knows about.

# Check if xclip is installed
if ! command -v xclip &> /dev/null; then
    notify-send "Nautilus Script" "Error: xclip is not installed."
    exit 1
fi

# Copy all paths to clipboard
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    echo "$file"
done | xclip -in -selection clipboard -f

# Notify the user
notify-send "Nautilus Script" "File paths copied to clipboard."
